services:

  webdav:
    image: hacdias/webdav
    container_name: goodnotes-webdav

    restart: unless-stopped

    environment:
      WEBDAV_USER: ${WEBDAV_USER}
      WEBDAV_PASSWORD: ${WEBDAV_PASSWORD}

    ports:
      - "8085:80"

    volumes:
      - /mnt/HDDStorage/DockerVolumes/KnowledgeStack/GoodNotes/webdav-inbox:/var/lib/dav
      - /opt/HomeLab/configs/KnowledgeStack/webdav/config.yml:/config.yml:ro
    
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.goodnotes.rule=Host(`goodnotes.tylerpac.dev`)"
      - "traefik.http.routers.goodnotes.entrypoints=web"

      - "traefik.http.routers.goodnotes.service=goodnotes"
      - "traefik.http.services.goodnotes.loadbalancer.server.port=80"

  couchdb:
    image: couchdb:3.4
    container_name: couchdb
    restart: unless-stopped

    environment:
      COUCHDB_USER: ${COUCHDB_ADMIN_USER}
      COUCHDB_PASSWORD: ${COUCHDB_ADMIN_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}

    volumes:
      - /mnt/HDDStorage/DockerVolumes/KnowledgeStack/CouchDB/data:/opt/couchdb/data
      - /opt/HomeLab/configs/KnowledgeStack/couchdb/local.ini:/opt/couchdb/etc/local.d/local.ini

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.couchdb.rule=Host(`couchdb.tylerpac.dev`)"
      - "traefik.http.routers.couchdb.entrypoints=web"
      - "traefik.http.routers.couchdb.service=couchdb"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"

  livesync-bridge:
    image: ghcr.io/vrtmrz/livesync-cli:latest
    container_name: livesync-bridge
    restart: unless-stopped

    depends_on:
      - couchdb

    volumes:
      - /mnt/HDDStorage/DockerVolumes/KnowledgeStack/LiveSyncBridge/state:/data
      - /mnt/HDDStorage/DockerVolumes/KnowledgeStack/ObsidianVault/SirPacsterVault:/vault

    command:
      - --settings
      - /data/settings.json
      - --vault
      - /vault
      - daemon

    networks:
      - proxy

networks:
  proxy:
    external: true